### ISSUE TITLE
The stack cookie security cookie was not properly initialized 	by the loader.

### ISSUE THREAD

**Issue by XiaoTouMingyo** [TheCruZ/kdmapper#103]
The stack cookie security cookie was not properly initialized
	by the loader.

**Comment by TheCruZ** [comment]
There is already a pull request about this, I didn't got time to test it https://github.com/TheCruZ/kdmapper/pull/100

**Comment by Jerem584** [comment]
Keep us informed if you have any troubles with the PR please.
