### ISSUE TITLE
can u please explain how to remove outputs 

### ISSUE THREAD

**Issue by ELJoOker2004** [TheCruZ/kdmapper#105]

**Comment by ELJoOker2004** [comment]
didn't understand :Note: Add definition DISABLE_OUTPUT to remove all console outputs

**Comment by TheCruZ** [comment]
Well as you say you only have to add DISABLE_OUTPUT definition to your project, which will be processed here:
https://github.com/TheCruZ/kdmapper/blob/5a49a4eec2abe0a4bd1f1b761a2733fed56a36aa/kdmapper/utils.hpp#L3
