### ISSUE TITLE
Windows 11, cant find pattern

### ISSUE THREAD

**Issue by Rene0220** [TheCruZ/kdmapper#106]
is it working on 22h2 build 22621.1555? i get error when try load driver, cant find pattern

**Comment by Rene0220** [comment]
![image](https://github.com/TheCruZ/kdmapper/assets/39531902/b3c542cc-ec19-4b29-b372-3d27382024ee)

**Comment by TheCruZ** [comment]
It worked, just used the fallback pattern, the only thing is that the driver that you load return 1 which depends on your code if it is good or bad
