### ISSUE TITLE
[+] DriverEntry returned 0xc0000001

### ISSUE THREAD

**Issue by Ripoffmyshoulders** [TheCruZ/kdmapper#108]
When my friends map the driver they get [+] DriverEntry returned 0x0 and i get 0xc0000001 and it is saying success at the end but in reality it doesnt map anything. Even i can map the driver at my other pc. Please help!

**Comment by TheCruZ** [comment]
Sorry but whatever returns the mapped driver entry is not related to kdmapper is related to the mapped driver.
PD: 0xC0000001 -> STATUS_UNSUCCESSFUL
