### ISSUE TITLE
Failed to map IO space of 0x0000000000000000

### ISSUE THREAD

**Issue by sysrom** [TheCruZ/kdmapper#111]
Windows 10 22H2 19045.3324

[<] Loading vulnerable driver, Name: vqiUaMuFOdtPVSzaO
[+] NtLoadDriver Status 0x0
[+] PiDDBLock Ptr 0xfffff8052f567028
[+] PiDDBCacheTable Ptr 0xfffff8052f567164
[-] Failed to map IO space of 0x0000000000000000
[-] Can't lock PiDDBCacheTable
[-] Failed to ClearPiDDBCacheTable
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink

**Comment by TheCruZ** [comment]
GetPhysicalAddress have failed returning physical address 0 and because of that can't map that memory, did you change anything or the hooked function (currently NtAddAtom)?

**Comment by sysrom** [comment]
No, I tried restarting my computer and it still prompted this

**Comment by sysrom** [comment]
It looks like the Kaspersky security software is causing the problem, previously I was using UCMapper but by chance after updating the Kaspersky database on 11/15/2023 UCM wasn't working properly either, after I uninstalled Kaspersky everything was back to normal :D
