### ISSUE TITLE
incorrect rand() usage

### ISSUE THREAD

**Issue by boris768** [TheCruZ/kdmapper#112]
https://github.com/TheCruZ/kdmapper/blob/5a49a4eec2abe0a4bd1f1b761a2733fed56a36aa/kdmapper/intel_driver.cpp#L122C76-L122C76

rand() returns some number from the range [ 0 , RAND_MAX ], RAND_MAX is compiler-specific value and msvc sets it as 0x7fff.
Since the number 2348767 is greater than any number that rand can return, the action of taking the remainder of the division has no effect

**Comment by TheCruZ** [comment]
Thanks fixed...
