### ISSUE TITLE
incorrect kernel memory free

### ISSUE THREAD

**Issue by boris768** [TheCruZ/kdmapper#118]
https://github.com/TheCruZ/kdmapper/blob/9152ffc46549ef8acafa0c2fd23059d08eb13ba4/kdmapper/kdmapper.cpp#L223

this cause bsod in mdl mode memory allocation, if do-while loop exit by break (i got it when added incorrect import)
 
i think it should be like this

```
  if (mdlMode) {
	  intel_driver::MmUnmapLockedPages(iqvw64e_device_handle, realBase, mdlptr);
	  intel_driver::MmFreePagesFromMdl(iqvw64e_device_handle, mdlptr);
	  intel_driver::FreePool(iqvw64e_device_handle, mdlptr);
  }
  else {
	  intel_driver::FreePool(iqvw64e_device_handle, realBase);
  }
```

**Comment by TheCruZ** [comment]
Thanks, makes sense

PD: i have noticed about your "mdlMode" variable, kdmapper was updated in last month with useful things that you may want
