### ISSUE TITLE
failed to load manifest

### ISSUE THREAD

**Issue by DanielSparta** [TheCruZ/kdmapper#119]
Hi, i started writing C# cheats for games because i think its a good way to get better at malware code writing, so i found this amazing project that i think is very cool, i have no any experience with rust so maybe its a stupid question..

i tried to run this command as the documentation says: cargo build --release
but it returning this error for me:
![image](https://github.com/TheCruZ/kdmapper/assets/111179755/1e3092e4-6620-45e3-9368-8e1bc17f6c8f)
I have tried to search for it on google but I dont really know what i am reading.

**how can i compile the vulthrun-driver.sys file? thanks alot!**

**Comment by TheCruZ** [comment]
This is not a kdmapper related issue
