### ISSUE TITLE
Virtual Machine Issue

### ISSUE THREAD

**Issue by stephenasuncionDEV** [TheCruZ/kdmapper#12]
It works on my main computer but when I use it on my vmware it wont go through.

On VMWare:
![Screenshot_1](https://user-images.githubusercontent.com/73958774/113375747-ec730a00-9324-11eb-95d1-635c4a74f4bc.png)

VMware windows version:
![1](https://user-images.githubusercontent.com/73958774/113375805-15939a80-9325-11eb-94b5-f21cfdc69b55.png)

My main computer windows version:
![2](https://user-images.githubusercontent.com/73958774/113375824-23492000-9325-11eb-93f2-3ec19ae205c0.png)

**Comment by TheCruZ** [comment]
I never try with Windows 10 Pro **N** but i will check it in any case

**Comment by TheCruZ** [comment]
Fixed, The list in Windows Pro **N** is empty
