### ISSUE TITLE
How to covert driver.sys about byte array

### ISSUE THREAD

**Issue by apkfer** [TheCruZ/kdmapper#121]
Hello, have a nice day I'm very sorry if this question is too stupid. 

**" if (!kdmapper::MapDriver(iqvw64e_device_handle, raw_image.data(), 0, 0, free, true, mode, passAllocationPtr, callbackExample, &exitCode))"** 

 As far as I know, this is the map driver line in byte code form (I think) Instead of manually using "kdamap.exe yourdr.sys" now I want yourdr to become 1 dr.h then I can use the other if part to loader, is that okay? Is there any documentation or examples on this problem, I don't know how to convert 1file.sys to byte array without corrupting it. Looking forward to receiving your answer. Thank you!

**Comment by TheCruZ** [comment]
Is something pretty simple and there are a lot of tools to do it, you can even do it by your self with a few lines of code using c++/python or whatever but here are an example code to do that conversion:
https://github.com/GH-Rake/Binary-To-AOB/blob/2447f40f4f4d78179e0e9fb945576e834065a6c7/Source.cpp#L7
