### ISSUE TITLE
Can't Use in Win 11 22H2

### ISSUE THREAD

**Issue by miguellealperez** [TheCruZ/kdmapper#122]
Hello guys, do you think I built it wrong? Does it not working on OS buid > 22621.2428?
![image](https://github.com/TheCruZ/kdmapper/assets/112134240/7420b698-0b07-4d8f-9d50-c2ce9f5bd678)

**Comment by TheCruZ** [comment]
Probably some antivirus/anticheat is intercepting intel driver to remove the vulnerability making the driver unusable, I can confirm that it works fine in that windows build

**Comment by Leonelyo** [comment]
![Bild_2023-12-22_030225885](https://github.com/TheCruZ/kdmapper/assets/154569425/cc90a884-e4c6-4d90-9e9a-f9d3daf832c1)
doesnt work for me there is no anti cheat in background

**Comment by Leonelyo** [comment]
![Bild_2023-12-22_030333899](https://github.com/TheCruZ/kdmapper/assets/154569425/aee0ce9e-dcbb-4c32-a273-10353c9af41e)
doesnt work for me there is no anti cheat in background

**Comment by jackdiddilysquad** [comment]
> ![Bild_2023-12-22_030333899](https://private-user-images.githubusercontent.com/154569425/292354603-aee0ce9e-dcbb-4c32-a273-10353c9af41e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzEwNDQsIm5iZiI6MTcwMzIzMDc0NCwicGF0aCI6Ii8xNTQ1Njk0MjUvMjkyMzU0NjAzLWFlZTBjZTllLWRjYmItNGMzMi1hMjczLTEwMzUzYzlhZjQxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwNzM5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWEyNWUwNjczZjYzZjMzMjY3N2Y0ZGNjZWNiYTRlYTgzY2RlMzJiY2NkMjZiN2Q0ZDQ5NTAzNTYxMDJlZjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MO-o0guJHTkjDDmMSVwb7S4iJwh6Jx1W2afPz8VvmWw) doesnt work for me there is no anti cheat in background i have an AMD Processor

i am also having this problem same version.

**Comment by TheCruZ** [comment]
Make sure you have:
All Antivirus **uninstalled** (Is possible that some modules to protect the kernel remain active even with protection disabled)
FACEIT, Vanguard and other anticheats **uninstalled**, this anticheats can't be disabled and some of them are working in background, and they can intercept the IOCTL of vulnerable drivers to modify it behavior like antivirus
HVCI (Memory protection) Disabled
Vulnerable driver list disabled
less common but can give you issues: make sure there is no any real iqvw64e driver installed in your system

If you did all this steps and still don't work you may try to disable virtualization in your BIOS if enabled to prevent any tool from using virtualization to protect the system

if still don't work, send a report of your system running "msinfo32 /nfo ./report.nfo" and I will try to check when I can

**Comment by Leonelyo** [comment]
> Make sure you have: All Antivirus **uninstalled** (Is possible that some modules to protect the kernel remain active even with protection disabled) FACEIT, Vanguard and other anticheats **uninstalled**, this anticheats can't be disabled and some of them are working in background, and they can intercept the IOCTL of vulnerable drivers to modify it behavior like antivirus HVCI (Memory protection) Disabled Vulnerable driver list disabled less common but can give you issues: make sure there is no any real iqvw64e driver installed in your system
> 
> If you did all this steps and still don't work you may try to disable virtualization in your BIOS if enabled to prevent any tool from using virtualization to protect the system
> 
> if still don't work, send a report of your system running "msinfo32 /nfo ./report.nfo" and I will try to check when I can

followed every step still doesnt work
virtualization doesnt exist in my BIOS, i disabled  the Vulnerable driver list and the other stuff is already disabled

it says "Failed to register and start service for the vulnerable driver"

**Comment by TheCruZ** [comment]
Show us the error code or a capture, but definitely that error isn't related with this issue

**Comment by dompurified** [comment]
you're getting STATUS_INVALID_DEVICE_REQUEST, are you sure you haven't loaded iqvw64e.sys or an old version of it somehow?

**Comment by jackdiddilysquad** [comment]
> Show us the error code or a capture, but definitely that error isn't related with this issue

when i launch kdmapper with my driver it just cloese at NtUnloadDriver status 0x0

**Comment by TheCruZ** [comment]
You must run kdmapper under a admin access console if you want to see the output

**Comment by Leonelyo** [comment]
> Show us the error code or a capture, but definitely that error isn't related with this issue

[<] Loading vulnerable driver, Name: IaMxivpzjrhgdL
[+] NtLoadDriver Status 0x0
[+] PiDDBLock Ptr 0xfffff8046853efac
[+] PiDDBCacheTable Ptr 0xfffff8046853f0e8
[+] PiDDBLock Locked
[+] Found Table Entry = 0xFFFF810A775B2360
[+] PiDDBCacheTable Cleaned
[+] g_KernelHashBucketList Found 0xFFFFF8046C8C2088
[+] g_HashCacheLock Locked
[+] Found In g_KernelHashBucketList: IaMxivpzjrhgdL
[+] g_KernelHashBucketList Cleaned
[+] MmUnloadedDrivers Cleaned: IaMxivpzjrhgdL
[+] WdFilter.sys not loaded, clear skipped
[+] Image base has been allocated at 0xFFFF98026E322000
[+] Skipped 0x1000 bytes of PE Header
[+] Load config directory wasn't found, probably StackCookie not defined, fix cookie skipped
[<] Calling DriverEntry 0xFFFF98026E322000
[+] Callback example called
[+] DriverEntry returned 0x0
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink
[+] success

using the HelloWorld driver example, DebugView doesnt show anything

**Comment by dompurified** [comment]
> > Show us the error code or a capture, but definitely that error isn't related with this issue
> 
> [<] Loading vulnerable driver, Name: IaMxivpzjrhgdL [+] NtLoadDriver Status 0x0 [+] PiDDBLock Ptr 0xfffff8046853efac [+] PiDDBCacheTable Ptr 0xfffff8046853f0e8 [+] PiDDBLock Locked [+] Found Table Entry = 0xFFFF810A775B2360 [+] PiDDBCacheTable Cleaned [+] g_KernelHashBucketList Found 0xFFFFF8046C8C2088 [+] g_HashCacheLock Locked [+] Found In g_KernelHashBucketList: IaMxivpzjrhgdL [+] g_KernelHashBucketList Cleaned [+] MmUnloadedDrivers Cleaned: IaMxivpzjrhgdL [+] WdFilter.sys not loaded, clear skipped [+] Image base has been allocated at 0xFFFF98026E322000 [+] Skipped 0x1000 bytes of PE Header [+] Load config directory wasn't found, probably StackCookie not defined, fix cookie skipped [<] Calling DriverEntry 0xFFFF98026E322000 [+] Callback example called [+] DriverEntry returned 0x0 [<] Unloading vulnerable driver [+] NtUnloadDriver Status 0x0 [+] Vul driver data destroyed before unlink [+] success
> 
> using the HelloWorld driver example, DebugView doesnt show anything

are you sure you're capturing kernel in DebugView? DriverEntry returned STATUS_SUCCESS, so i don't feel like this is a kdmapper issue

**Comment by TheCruZ** [comment]
> > Show us the error code or a capture, but definitely that error isn't related with this issue
> 
> [<] Loading vulnerable driver, Name: IaMxivpzjrhgdL [+] NtLoadDriver Status 0x0 [+] PiDDBLock Ptr 0xfffff8046853efac [+] PiDDBCacheTable Ptr 0xfffff8046853f0e8 [+] PiDDBLock Locked [+] Found Table Entry = 0xFFFF810A775B2360 [+] PiDDBCacheTable Cleaned [+] g_KernelHashBucketList Found 0xFFFFF8046C8C2088 [+] g_HashCacheLock Locked [+] Found In g_KernelHashBucketList: IaMxivpzjrhgdL [+] g_KernelHashBucketList Cleaned [+] MmUnloadedDrivers Cleaned: IaMxivpzjrhgdL [+] WdFilter.sys not loaded, clear skipped [+] Image base has been allocated at 0xFFFF98026E322000 [+] Skipped 0x1000 bytes of PE Header [+] Load config directory wasn't found, probably StackCookie not defined, fix cookie skipped [<] Calling DriverEntry 0xFFFF98026E322000 [+] Callback example called [+] DriverEntry returned 0x0 [<] Unloading vulnerable driver [+] NtUnloadDriver Status 0x0 [+] Vul driver data destroyed before unlink [+] success
> 
> using the HelloWorld driver example, DebugView doesnt show anything

Kdmapper work fine in that case

**Comment by TheCruZ** [comment]
I will close this issue since no more updates and looks more like an issue in people configuration or wrong usage
