### ISSUE TITLE
[-] Failed to register and start service for the vulnerable driver

### ISSUE THREAD

**Issue by crazyguy103932** [TheCruZ/kdmapper#126]
kdmapper used to work for me before i reinstalled windows, now that i did im getting this error wich idk why or how to fix
winver : 22h2 win10
please help if possible

**Comment by TheCruZ** [comment]
You didn't specify the error code or a image with the error

**Comment by crazyguy103932** [comment]
its fixed
i just had to uninstall my windows security update

**Comment by fnguyy** [comment]
> its fixed i just had to uninstall my windows security update

Could you please say which security patch you had to uninstall to fix the issue?
