### ISSUE TITLE
Problem loading driver

### ISSUE THREAD

**Issue by scemmaz** [TheCruZ/kdmapper#127]
So im trying to load this basic driver.
![Bild_2024-01-31_172949708](https://github.com/TheCruZ/kdmapper/assets/120191423/8352271b-f278-483c-b613-f3bb59ba2053)
And im keep getting this error, i disabled secure boot and enabled windows debugging but still it wont work any help please?
![Bild_2024-01-31_172928739](https://github.com/TheCruZ/kdmapper/assets/120191423/7103ee17-aad6-40ab-b044-06163f681b1c)

**Comment by scemmaz** [comment]
> That error isn't related to the target driver, is caused by some antivirus and anticheats in background

I have now disabled my antivirus and could't find any anticheats in background. And still get this:
![Bild_2024-01-31_180343542](https://github.com/TheCruZ/kdmapper/assets/120191423/55eaf73c-aa7e-423b-bde2-bd1a81460e9d)

**Comment by scemmaz** [comment]
> That error isn't related to the target driver, is caused by some antivirus and anticheats in background

Nvm i fixed it thanks for the help :)

**Comment by TheCruZ** [comment]
please leave your solution for other users

**Comment by scemmaz** [comment]
> please leave your solution for other users

It still wasnt working on my pc after i diasbled my Antivirus and anticheats in background, so i created a windows VM on that it worked. (there must to be something else blocking it on my pc but i dont know what.)

**Comment by AndrewKellyDev** [comment]
Im also getting the same error
