### ISSUE TITLE
Failed to find pattern for WdFilters

### ISSUE THREAD

**Issue by Jueshh** [TheCruZ/kdmapper#128]
It says that 

Failed to find WdFilter MpFreeDriverInfoEx

and all others WdFilter patterns..

**Comment by Jueshh** [comment]
My bad hehe I did not even see the update

**Comment by miss137001** [comment]
DFO Global Support (Neople)
Feb 8, 2024, 13:12 GMT+9


Greetings Adventurer!
&nbsp;
Thanks for reaching out to us about your account.
&nbsp;
I totally get where you're coming from. It seems like there was a bit of a hiccup with the Terms of Service, and that led to a permanent restriction on your account.
&nbsp;
Unfortunately, reversing the sanction is just not in the cards.
&nbsp;
We know it's not the news you were hoping for. But we're still here to help with anything else you need.
&nbsp;
Best Regards,
&nbsp;
Shinjang




发自我的iPhone


------------------ Original ------------------
From: Jueshh ***@***.***&gt;
Date: Fri,Feb 9,2024 8:21 PM
To: TheCruZ/kdmapper ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [TheCruZ/kdmapper] Failed to find pattern for WdFilters (Issue#128)





 
My bad hehe I did not even see the update
