### ISSUE TITLE
i cant map my driver

### ISSUE THREAD

**Issue by maxiwee69** [TheCruZ/kdmapper#129]
when i try to run  my driver as admin i get `C:\Users\maxi\source\repos\driver\build>kdmapper_Release.exe kernelmode.sys
[<] Loading vulnerable driver, Name: GFhytgxqdkysfZHBJcdfcus
[+] NtLoadDriver Status 0xc0000603
[-] Failed to register and start service for the vulnerable driver`

av is completly off, testsigning is on my win version is 23h2

**Comment by TheCruZ** [comment]
You need to disable vulnerable driver list, please take a minute of reading the README before create an issue

**Comment by maxiwee69** [comment]
this option doesnt appear for me

**Comment by maxiwee69** [comment]
what key do i need to edit for that
