### ISSUE TITLE
Issue with mapping driver Win 11 23h2

### ISSUE THREAD

**Issue by Random-Cod3r** [TheCruZ/kdmapper#130]
So let me start off by saying I'm very new when it comes to developing drivers. Im using the HelloWorld from this project and when i try to load it it just runs a cmd window and instantly closes. I sent it to a friend who is on win 10 22h2 and it worked and mapped properly. So i'm wondering if it is a me issue or a issue with the mapper itself.

--Edit:

I have also added std::cin.get(); to everywhere the script returns to try and get it to work but that didn't do anything either

**Comment by TheCruZ** [comment]
You just need to open kdmapper with a CMD with admin rights to see the output and your possible issue

**Comment by DokiOnLowest** [comment]
Im having the same problem

**Comment by TheCruZ** [comment]
I will close the issue until there is not real information about the issue
