### ISSUE TITLE
Failed to find WdFilter MpFreeDriverInfoEx

### ISSUE THREAD

**Issue by shaygitub** [TheCruZ/kdmapper#134]
im using an 1809 vm, kdmapper worked perfectly on the machine and i didnt change anything in the kdmapper build / the mapped driver. kdmapper fails constantly with the same error that is shown in the picture. its not a problem with my driver as it also fails with the HelloWorld driver.
![dsadsadsadsadsadsa](https://github.com/TheCruZ/kdmapper/assets/122000611/ba3cc414-22e1-451e-a6a2-da20d29aa727)

**Comment by TheCruZ** [comment]
Hi, the problem is that wdfilter was updated in the last months, are you using last build of kdmapper which brings some extra patterns?

**Comment by shaygitub** [comment]
> Hi, the problem is that wdfilter was updated in the last months, are you using last build of kdmapper which brings some extra patterns?

Yes i do use the last build of kdmapper. Although the os version is 1809 so it shouldn't really change anything. Ill try in a few hours to download the source code and even compile it again
