### ISSUE TITLE
NT.hpp issue errors

### ISSUE THREAD

**Issue by roralsorom** [TheCruZ/kdmapper#135]
When I include kdmapper source to my source it gives me a bunch of errors from nt.hpp im not sure why

![image](https://github.com/TheCruZ/kdmapper/assets/86061161/26c0aca4-695c-4f4d-832e-4d9fa71fa388)

![image](https://github.com/TheCruZ/kdmapper/assets/86061161/485d5c65-1de2-44a7-bf6b-2bf7499c34bd)

![image](https://github.com/TheCruZ/kdmapper/assets/86061161/338541a4-7887-45d6-9a76-07ff14bfe807)

**Comment by addressnopping** [comment]
hello, what did u do to fix that issue?
