### ISSUE TITLE
kdmapper x32

### ISSUE THREAD

**Issue by Jacellen** [TheCruZ/kdmapper#136]
I need to compile kdmapper x86, what should I change to do this?

**Comment by Jacellen** [comment]
@TheCruZ

**Comment by TheCruZ** [comment]
This week I'm not at home but what you need can be a complex task and I don't know the reason at all, some years ago windows removed x86 support for kernel and this means you want to use kdmapper for a windows 7 with 4gb of ram or so? If you want to do this you need to find the x86 version of the vulnerable driver and it's structure if changed, then compile kdmapper and verify that every structure match your x86 kernel, now you will need update the patterns and you will be ready to go
