### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Xvvn** [TheCruZ/kdmapper#14]
The application was unable to start correctly (0xc000007b).

Does anyone know what's wrong?

**Comment by TheCruZ** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
did you change the vuln driver or in general is you target driver fine?

**Comment by Xvvn** [comment]
driver is working on other pcs but one of my friends had originally got a vcruntime_140.dll issue and he had downloaded the missing dll which probably fucked something up and now we are getting 0xc000007b

**Comment by TheCruZ** [comment]
vcruntime_140.dll is because he don't have Microsoft redistributables installed, error 0xc000007b shouldn't happen if you are providing the driver correctly, and you didn't modify the intel driver

**Comment by TheCruZ** [comment]
Closed after 4 days of inactivity
