### ISSUE TITLE
Returns success, but file not created. Error code 2.

### ISSUE THREAD

**Issue by Ben00n** [TheCruZ/kdmapper#140]
i get error code 2, file not found.
My code is alright. it did work before, now it doesn't. code never changed on both ends.

winver perhaps?

![image](https://github.com/TheCruZ/kdmapper/assets/72699618/da335a78-cdf5-47a2-a1e6-5be359b13452)

**Comment by TheCruZ** [comment]
The issue is not related to kdmapper, your driver returned 0xC0000035
