### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by CowNowK** [TheCruZ/kdmapper#141]
![image](https://github.com/TheCruZ/kdmapper/assets/133740174/00314d73-b1df-4fc8-8650-adce3db71036)
Is this a problem with my driver?
I am working on Win11 23H2 22631.3296

**Comment by TheCruZ** [comment]
You are running the CMD probably as usermode, then kdmapper executes on a separate context of the CMD and you don't see the output, you must launch the CMD as admin

**Comment by CowNowK** [comment]
Thanks for reminding, now it works
![image](https://github.com/TheCruZ/kdmapper/assets/133740174/2f4a1932-1e84-4d46-9fbf-0df8efde14fe)

But I got a new error message, which part is this usually a problem with?

**Comment by TheCruZ** [comment]
As README says you have enable vulnerable driver list and you must disable it to use kdmapper

**Comment by CowNowK** [comment]
btw, I have modified the Register according to the readme. But I didn't restart the computer, I just logged out of my Windows login and logged back in. I don't know if this has any effect, although most of the time this method can be effectively replaced by restarting

**Comment by CowNowK** [comment]
![image](https://github.com/TheCruZ/kdmapper/assets/133740174/51875240-523b-41b1-93a3-24350ee22309)
Thank you very much for help, the last question, I refer to another issue #27 , this seems to a problem of kdmapper or Windows?
