### ISSUE TITLE
Can't find pattern issue

### ISSUE THREAD

**Issue by chamsdlr** [TheCruZ/kdmapper#142]
After the newest windows update i cant load drivers anymore. It just says "can't find pattern

_[<] Loading vulnerable driver, Name: NnbhHotHCznvMbzRXITGMUnqUxQ
[+] NtLoadDriver Status 0x0
[-] Can't find pattern
[+] PiDDBLock found with second pattern
[+] PiDDBLock Ptr 0xfffff8052fa3a1fa
[+] PiDDBCacheTable Ptr 0xfffff8052f958e58
[+] PiDDBLock Locked
[+] Found Table Entry = 0xFFFFAB0CED354D30
[+] PiDDBCacheTable Cleaned
[+] g_KernelHashBucketList Found 0xFFFFF8052CB7F088
[+] g_HashCacheLock Locked
[+] Found In g_KernelHashBucketList: NnbhHotHCznvMbzRXITGMUnqUxQ
[+] g_KernelHashBucketList Cleaned
[+] MmUnloadedDrivers Cleaned: NnbhHotHCznvMbzRXITGMUnqUxQ
[-] Can't find pattern
[+] Found WdFilter MpFreeDriverInfoEx with second pattern
[+] WdFilterDriverList Cleaned: \Users\Leo\AppData\Local\Temp\NnbhHotHCznvMbzRXITGMUnqUxQ
[+] Image base has been allocated at 0xFFFF9A86DD0B0000
[+] Skipped 0x1000 bytes of PE Header
[+] Load config directory wasn't found, probably StackCookie not defined, fix cookie skipped
[<] Calling DriverEntry 0xFFFF9A86DD0B0050
[+] Callback example called
[+] DriverEntry returned 0xcf000004
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink
[+] success_

**Comment by maecry** [comment]
[+] DriverEntry returned 0xcf000004
And
[+] success ?

**Comment by TheCruZ** [comment]
That return is user defined and not related to kdmapper, kdmapper can't determine if your driver process correctly or not, the patterns has been found correctly with second try
