### ISSUE TITLE
no output dbgView

### ISSUE THREAD

**Issue by iinQ1337** [TheCruZ/kdmapper#143]
![image](https://github.com/TheCruZ/kdmapper/assets/106882763/1cd1da8c-e22e-43b1-88e9-b6dd5bda80c5)

In dbgView, I am not getting any messages. It seems like the driver is simply not loading

**Comment by TheCruZ** [comment]
Change the return code in the code of the driver and execute again with kdmapper, if the returned code changes kdmapper works fine and you have an issue with dbgview
