### ISSUE TITLE
[-] Driver Unload Failed!!

### ISSUE THREAD

**Issue by IvanAstran** [TheCruZ/kdmapper#145]
[<] Loading vulnerable driver, Name: GYhcycvwBxNPnkCrYQMwAHuzynRcy
[+] NtLoadDriver Status 0x0
[-] Can't read module headers
[-] No module address to find pattern
[-] Can't read module headers
[-] No module address to find pattern
[-] Can't read module headers
[-] No module address to find pattern
[-] Warning PiDDBLock not found
[-] Failed to ClearPiDDBCacheTable
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0xc0000010
[-] Driver Unload Failed!!

**Comment by TheCruZ** [comment]
Some antivirus or anticheat is blocking the vulnerable driver

**Comment by alec2112346** [comment]
gf
