### ISSUE TITLE
Failed to get ntoskrnl.exe ( Windows 11 24H2 )

### ISSUE THREAD

**Issue by Jueshh** [TheCruZ/kdmapper#148]
It says Failed to get ntoskrnl.exe

![image](https://github.com/user-attachments/assets/686ec97f-d8a5-47ae-af27-9f153b079071)

Something weird is going on..

**Comment by mmkingdestroye** [comment]
https://github.com/TheCruZ/kdmapper/issues/120

**Comment by TheCruZ** [comment]
Fixed https://github.com/TheCruZ/kdmapper/commit/5c83427142f0b6f6d72302d1e6c618bc875c3489
