### ISSUE TITLE
With the official release of Window 11 24H2 (26100.1882), Kdmapper failed to get ntoskrnl.exe

### ISSUE THREAD

**Issue by SonThanhVN** [TheCruZ/kdmapper#152]
![image](https://github.com/user-attachments/assets/bb6cc5d1-fbc9-49d7-b30f-93b967c36677)

**Comment by TheCruZ** [comment]
I still didn't upgrade my windows version, but probably you just have to give kdmapper privileges, for the other side a pull request with new kdmapper patterns has been approved

**Comment by TheCruZ** [comment]
Fixed https://github.com/TheCruZ/kdmapper/commit/5c83427142f0b6f6d72302d1e6c618bc875c3489

**Comment by p4ragoNn** [comment]
> Fixed [5c83427](https://github.com/TheCruZ/kdmapper/commit/5c83427142f0b6f6d72302d1e6c618bc875c3489)

All good, worked like a charm. Thanks!! @TheCruZ
