### ISSUE TITLE
Doing Nothing on new Windows Build (no printouts, no mapping, nothing...)

### ISSUE THREAD

**Issue by GKlokowski** [TheCruZ/kdmapper#153]
![{9B7F2E93-0712-4C23-A138-A2370783ED16}](https://github.com/user-attachments/assets/a48441af-4e71-4b82-add3-f510a7440bcb)

**Comment by TheCruZ** [comment]
You are not using a new windows build, make sure you didn't define "DISABLE_OUTPUT"
