### ISSUE TITLE
stop working after Callback exemple called

### ISSUE THREAD

**Issue by xbet95** [TheCruZ/kdmapper#154]
![image](https://github.com/user-attachments/assets/a93645da-7988-47f6-8e4c-fd699fc31e88)
It seems I can't resolve this issue, nor can I find any solutions. When loading any drivers, kdmapper appears to stop functioning after calling DriverEntry, and it doesn't unload the vulnerable driver. Thanks for helping on this

**Comment by TheCruZ** [comment]
That's because you didn't read the Readme in the section requirements https://github.com/TheCruZ/kdmapper?tab=readme-ov-file#requirements it says that you must return from your driver entry fast as you can, and probably you are entering in some while/waitfor state without return

**Comment by xbet95** [comment]
i tried multiples drivers from github and they all result the same
it looks like this : 

NTSTATUS DriverEntry() {
    debug_print("[+] DriverEntry Called\n");

    UNICODE_STRING driver_name = {};
    RtlInitUnicodeString(&driver_name, L"\\Driver\\TestDriver");

    return IoCreateDriver(&driver_name, &driver_main);
}

**Comment by TheCruZ** [comment]
You are using default kdmapper without modify anything with the helloworld driver? also, which windows version are you using?

**Comment by xbet95** [comment]
Fixed by removing a useless line in kdmapper that prevented the return at the callback fonction as you guessed.
Mb sir and thanks
