### ISSUE TITLE
[-] Failed to get ntoskrnl.exe (24h2)

### ISSUE THREAD

**Issue by Disshi300** [TheCruZ/kdmapper#156]
[<] Loading vulnerable driver, Name: HogzoYgZgMTlFzLHRCdQk
[+] NtLoadDriver Status 0x0
[-] Failed to get ntoskrnl.exe
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink

fix?

**Comment by TheCruZ** [comment]
Probably you are not using latest kdmapper version 
Fixed at:
https://github.com/TheCruZ/kdmapper/commit/5c83427142f0b6f6d72302d1e6c618bc875c3489

**Comment by Disshi300** [comment]
Yes I am

**Comment by TheCruZ** [comment]
Can you debug this function https://github.com/TheCruZ/kdmapper/blob/74e33e29255e6884dc6bdc0c037ede4da68aeeed/kdmapper/utils.cpp#L40 and show if modules can be retrieved or what is going on?
