### ISSUE TITLE
My driver bsoding PAGE_FAULT_IN_NONPAGED_AREA error

### ISSUE THREAD

**Issue by Infinitydagestan** [TheCruZ/kdmapper#157]
Driver entrypoint 
![image](https://github.com/user-attachments/assets/9869e162-7419-4172-85a7-384a4d2be154)

**Comment by TheCruZ** [comment]
Please check the readme:
https://github.com/TheCruZ/kdmapper?tab=readme-ov-file#parameters

Entry point parameters are null
