### ISSUE TITLE
VulnerableDriverBlocklistEnable reg

### ISSUE THREAD

**Issue by Cyk-Fad** [TheCruZ/kdmapper#159]
REGEDIT4
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Config]
"VulnerableDriverBlocklistEnable"=-
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Config]
"VulnerableDriverBlocklistEnable"=dword:00000000

this may work?

**Comment by TheCruZ** [comment]
Probably yes
