### ISSUE TITLE
Windows 11 official release

### ISSUE THREAD

**Issue by GabrielBigardi** [TheCruZ/kdmapper#16]
Hi, i was planning to use kdmapper tool, but i'm currently on the windows 11 pro official release (windows 11 21h2 22000.51), is there any plan to add support to this windows version any time soon ? Thanks.

**Comment by TheCruZ** [comment]
I don't see any issue in Windows 22000.51
![image](https://user-images.githubusercontent.com/23271181/124035110-61c1aa00-d9fc-11eb-9d43-dc9e9eac5911.png)

**Comment by GabrielBigardi** [comment]
Hi, it was just a error in my driver, seems to be working properly, thank you!

**Comment by TheCruZ** [comment]
np

**Comment by vladmirklovs** [comment]
I have a problem, I can not run kdmapper, it opens and closes, before I have formatted my computer, ran normally

**Comment by SoarCheats** [comment]
> I have a problem, I can not run kdmapper, it opens and closes, before I have formatted my computer, ran normally

because you have to add params, you cant just run kdmapper without any arguments to map 😭
