### ISSUE TITLE
Error while loading driver

### ISSUE THREAD

**Issue by DenxizGithub** [TheCruZ/kdmapper#163]
[<] Loading vulnerable driver
[+] NtLoadDriver Status 0x0
[-] Failed to get ntoskrnl.exe
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink

**Comment by TheCruZ** [comment]
This was fixed at https://github.com/TheCruZ/kdmapper/commit/5c83427142f0b6f6d72302d1e6c618bc875c3489
please use latest version
