### ISSUE TITLE
 Failed to register and start service for the vulnerable driver

### ISSUE THREAD

**Issue by dylang20** [TheCruZ/kdmapper#19]
Hello

Cannot seem to get this to work at all, no anti-virus running, windows defender completely disabled.

`[<] Loading vulnerable driver, Name: tZhrseVFgBikCWt
[+] NtLoadDriver Status 0xc000009a
[-] Failed to register and start service for the vulnerable driver`

as NTLoadDriver is displaying - STATUS_INSUFFICIENT_RESOURCES

Compiled for Release Mode, x64 - Winver 21H1 19043.110

**Comment by sebsi45** [comment]
How did you fix it, im having the same issue!

**Comment by DanielSparta** [comment]
how to fix it?

**Comment by TheCruZ** [comment]
Please read the readme of the project 0xc000009a is mostly caused by FACEIT and other anticheat-antivirus softwares....

**Comment by DanielSparta** [comment]
> Please read the readme of the project 0xc000009a is mostly caused by FACEIT and other anticheat-antivirus softwares....

hi, the reason its happening is because Windows 11 defender have a new method which blocks some apps that are trying to run a kernel mode code. At windows 10 this future not exist. I dont sure if its possible to disable this windows 11 future by 100%

**Comment by TheCruZ** [comment]
You are speaking about error 603 which is also explained in this repository and just requires disable vulnerable driver list on windows defender
