### ISSUE TITLE
Using --mdl and nulling pfn causes bsod

### ISSUE THREAD

**Issue by gandaalv** [TheCruZ/kdmapper#25]
OS: Windows 20H2
Using TygoL's build with --mdl flag and same driver works as expected.

**Comment by TheCruZ** [comment]
tygol --mdl flag makes mdl ptr sent by the first param of the driver entry while in this code the first param will be 0 or the base address of the allocation in case that you set PassAllocationAddressAsFirstParam

You can use the callback function if you want to pass the mdl ptr into the driver entry params more or less like this:

`bool callbackExample(ULONG64* param1, ULONG64* param2, ULONG64 allocationPtr, ULONG64 allocationSize, ULONG64 mdlptr) {
	*param1 = mdlptr;
	return true;
}`
