### ISSUE TITLE
wrong?

### ISSUE THREAD

**Issue by GerritdinaH** [TheCruZ/kdmapper#26]
https://github.com/TheCruZ/kdmapper/blob/25747774c108063ee9269c64c7deae3a6da0bcdd/kdmapper/kdmapper.cpp#L146

i think this line is wrong, as i just BSOD all the time until i looked at the code, i think it should be the following:
`if (!intel_driver::CallKernelFunction(iqvw64e_device_handle, &status, address_of_entry_point, (mdlMode ? mdlptr : (PassAllocationAddressAsFirstParam ? realBase : param1)), param2)) {`

otherwise mdl mode will BSOD

**Comment by TheCruZ** [comment]
https://github.com/TheCruZ/kdmapper/issues/25

PassAllocationAddressAsFirstParam is designed to send the allocation address and not the mdl ptr, the the closed issue if your want your work around
