### ISSUE TITLE
Failed to map driver

### ISSUE THREAD

**Issue by GraterThumbleed** [TheCruZ/kdmapper#27]
> [<] Loading vulnerable driver, Name: QvxVqegYVXXFT
> [+] NtLoadDriver Status 0x0
> [-] Can't find pattern
> [-] Warning no PiDDBCacheTable Found
> [-] Failed to ClearPiDDBCacheTable
> [<] Unloading vulnerable driver
> [+] NtUnloadDriver Status 0x0
> [+] Vul driver data destroyed before unlink

This may be due to my windows version being Windows 11 22449.1000 can I get a confirmation?

**Comment by TheCruZ** [comment]
Are you using the latest commit? I will check tomorrow if I have time with that Windows version

**Comment by GraterThumbleed** [comment]
Ye Im using the latest commit

**Comment by TheCruZ** [comment]
Yes version 22449 breaks the pattern again I will fix the pattern later when I got time

**Comment by TheCruZ** [comment]
Update pushed
