### ISSUE TITLE
please teach me

### ISSUE THREAD

**Issue by xxTree** [TheCruZ/kdmapper#30]
If I try to use PsSetCreateProcessNotifyRoutine, it will return 0xc0000022. If I use KsInitialize, it will directly blue screen. Is there any solution? thanks！

**Comment by TheCruZ** [comment]
PsSetCreateProcessNotifyRoutine Should be called from a valid module memory and set the callback location in a valid module memory else patchguard will BSOD you after a little while and kdmapper by default just allocate a simple Memory Pool

About KsInitialize I understand that you are speaking about KSOCKET module for kernel and I don't know why you get bsod check the BSOD file to get the BSOD location in your source
