### ISSUE TITLE
Why does it just blue screen every time I load my driver?

### ISSUE THREAD

**Issue by YoAvrageBiTz** [TheCruZ/kdmapper#36]
I am just confused why it fails to load my driver every time. I am on 21h1 and am running a UserMode driver for an injection method, does not want to work. If anyone might have an explanation that would be great!
Edit: I have secure boot off, virtualization off and the BSOD message is KERNEL_SECURITY_CHECK_FAILURE

**Comment by TheCruZ** [comment]
KERNEL_SECURITY_CHECK_FAILURE means that you are doing something that windows don't allow from a mapped memory, like for example setting up a callback outside valid module which is forbidden by PatchGuard
