### ISSUE TITLE
PFN BSOD

### ISSUE THREAD

**Issue by Shankyournan** [TheCruZ/kdmapper#39]
If i use --mdl and I interact in anyway with the mdlptr i get a SYSTEM_SERVICE_EXCEPTION bsod. I have no idea why though. Here is my DriverEntry. If you know why tf its happening please help.

`NTSTATUS DriverEntry(ULONG64* useless1, ULONG64* useless2, ULONG64 allocationPtr, ULONG64 allocationSize, ULONG64 mdlptr) 
{ 
    UNREFERENCED_PARAMETER(useless1);
    UNREFERENCED_PARAMETER(useless2);
    UNREFERENCED_PARAMETER(allocationPtr);
    UNREFERENCED_PARAMETER(allocationSize);
    PMDL mdl = (PMDL)mdlptr;
    return true; 
}`

**Comment by llxiaoyuan** [comment]
__stdcall ？

**Comment by Shankyournan** [comment]
NTSTATUS _stdcall DriverEntry didnt work either same bsod code.

**Comment by TheCruZ** [comment]
Driver entry only have 2 params and since you wrote more on it by one side maybe the compiler didn't found it, by other side kdmapper only send 2 params by default and may get some exception on return

**Comment by Shankyournan** [comment]
Fixed added the mdlptr to the CallKernelFunction arguments thanks for the help.
