### ISSUE TITLE
page fault in nonpaged area

### ISSUE THREAD

**Issue by kyrox02** [TheCruZ/kdmapper#40]
im trying using this injector https://github.com/Rhydon1337/windows-kernel-dll-injector with kdmapper  i got bsod 
page fault in nonpaged area i try disable Security checks -GS + set DriverEntry without luck what could it be ?

**Comment by TheCruZ** [comment]
Check the address in your BSOD file but if you didn't change anything https://github.com/Rhydon1337/windows-kernel-dll-injector/blob/467ec97eaaed1828cf2918a211539d42af047d98/DLLInjector/DLLInjector/main.cpp#L15 this entry point receive null pointers in manual map, which means that will automatically BSOD when the code try to access them

for example here
https://github.com/Rhydon1337/windows-kernel-dll-injector/blob/467ec97eaaed1828cf2918a211539d42af047d98/DLLInjector/DLLInjector/main.cpp#L25
or here
https://github.com/Rhydon1337/windows-kernel-dll-injector/blob/467ec97eaaed1828cf2918a211539d42af047d98/DLLInjector/DLLInjector/main.cpp#L34

**Comment by kyrox02** [comment]
Thank u SO MUCH IoCreateDriver Fixed it !
![vsa](https://user-images.githubusercontent.com/27238585/145708125-2928c803-6f68-4cac-8d4f-482809e23139.png)
