### ISSUE TITLE
Crash on loading vuln driver

### ISSUE THREAD

**Issue by X3P0** [TheCruZ/kdmapper#43]
Processor: 12th Gen Intel(R) Core(TM) i9-12900K
OS Build: Windows 11 22000.376

https://support.microsoft.com/en-us/topic/december-14-2021-kb5008215-os-build-22000-376-868d2c2f-a201-456e-be42-d95c794bebf0

Crashing on first step in kdmapper using HelloWorld driver

[<] Loading vulnerable driver, Name: 123456
.. Then BSOD/Crash

**Comment by TheCruZ** [comment]
I'm trying in a VM with that update installed at 22000.376 and is working fine with Hello World

Windows 11 will/or already have 2 things to prevent tools like kdmapper, one is a virtualized security to prevent bad executions and the other one is block vulnerable drivers by some way, but in the VM is working fine then they keep featured disabled on VM or still not exists

**Comment by TheCruZ** [comment]
Close after no response, I can't reproduce the issue
