### ISSUE TITLE
Getting STATUS_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by LethalSnake1337** [TheCruZ/kdmapper#44]
Hey do you know why I am getting a STATUS_INSUFFICIENT_RESOURCES when calling NtLoadDriver?

I saw in the closed tickets that someone had the same issue but he didn't posted any solution.

**Comment by TheCruZ** [comment]
Is in the main readme of the project 😵‍💫 

0xC000009A == STATUS_INSUFFICIENT_RESOURCES

https://github.com/TheCruZ/kdmapper#errors-0xc0000022-and-0xc000009a
