### ISSUE TITLE
nothing work(no output)

### ISSUE THREAD

**Issue by leon070704** [TheCruZ/kdmapper#53]
hello, after my last windows 11 update is the kdmapper not working(no console output) the problem is only on my pc. My frind has testet it.

i have tryed my own driver & the helloworld driver.

My system: I7-7700k,  Windows 11 21H2 22000.469

**Comment by EinTim23** [comment]
this doesnt happen to me with the latest win 11 stable build that got the same build number. I use a modified Version of this project tho.

**Comment by TheCruZ** [comment]
Closed since no response
