### ISSUE TITLE
the application was unable to start correctly 0xc00007b

### ISSUE THREAD

**Issue by ToreFPS** [TheCruZ/kdmapper#54]
I have all the runtimes installed, directx runtime aswell no clue why im getting this error. Got runtime dll errors and msvcp errors before installing runtimes now i just get "the application was unable to start correctly 0xc00007b"
Any clue why?

**Comment by TheCruZ** [comment]
Remove and reinstall your 2019 runtimes https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

if you built it as debug, make sure you are doing it as release, if the error disappear as release you don't have debug redistributes normally installed with dev environments
