### ISSUE TITLE
MouClassInputInjection

### ISSUE THREAD

**Issue by kpolicar** [TheCruZ/kdmapper#6]
Hello!

Firstly, this is not an issue. I was hoping you might be able to help me / give me some insight as to why I can't load this driver with kdmapper? I'm new to driver programming, so the issue may be obvious.
The driver loads just fine if loaded normally, with test signing enabled through sc.exe

The rest of the details I've mentioned here:
https://github.com/changeofpace/MouClassInputInjection/issues/11

**Comment by TheCruZ** [comment]
Probably because you didn't set a custom entry point in the project settings, you have GsDriverEntry, which and a lot of stuff that maybe by some reason didn't finally call to your DriverEntry to run the "IoCreateDriver"
