### ISSUE TITLE
I got kernel-security-check-failure BSOD

### ISSUE THREAD

**Issue by OkabeRintarou1** [TheCruZ/kdmapper#61]
#include <ntifs.h>
#include <ntddk.h>

extern "C" NTSTATUS DriverEntry(unsigned __int64 a1, unsigned __int64 a2)
{
	DbgPrintEx(0, 0, "yes\n");

	return STATUS_SUCCESS;
}
This is my code
Everything is set by default. What did I do wrong

**Comment by BuddyBoi** [comment]
With the plan repo I also started getting a related error no matter what. 
I'm not sure exactly what it is, but a heavily modified but same idea old branch works just fine for me.

**Comment by BuddyBoi** [comment]
Have you tried disabling security check?
Option is referenced as /GS.

**Comment by TheCruZ** [comment]
Did you set the custom entry point?

**Comment by TheCruZ** [comment]
Closed since the owner didn't answer
