### ISSUE TITLE
MSVCP140D.dll error when trying to open

### ISSUE THREAD

**Issue by Com3Carne** [TheCruZ/kdmapper#62]
Every time I try to open the program, I get this error. I have all Visual Basic installed on my computer
Can you tell me what could be going on?

**Comment by EinTim23** [comment]
Hello,
You will need the latest x64 visual c++ redistributable for this to work. You can download it [here](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by TheCruZ** [comment]
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Anyway take care D.dll at the end of the name means that you are compiling it as debug and if you want only test it I recommend you to build as release
