### ISSUE TITLE
21H2 BSOD

### ISSUE THREAD

**Issue by VSEdison** [TheCruZ/kdmapper#64]
win10 1607, 1809, 20h2, win11 are normal, 21h2 bsod
Crash code is KMODE_EXCEPTION_NOT_HANDLED

**Comment by TheCruZ** [comment]
KMODE_EXCEPTION_NOT_HANDLED occurs if anything on your code generate an exception since kdmapper don't support exceptions on manually mapped code, check your BSOD and verify where your code gives the exception for BSOD
