### ISSUE TITLE
mdl bsod.

### ISSUE THREAD

**Issue by Cfinn237** [TheCruZ/kdmapper#68]
Why does freeing MDL from kdmapper bsod me only when using mdl in kernel to write to read only memory.

**Comment by TheCruZ** [comment]
Sorry but i didn't test too many times the mdl mode since was made by another contributor, are you executing anything in that memory in the moment of freeing?, you must remove any thread, callback or execution before free the memory

**Comment by TheCruZ** [comment]
Closed after no response
