### ISSUE TITLE
BSOD   page fault in nonpaged area

### ISSUE THREAD

**Issue by leidadpig** [TheCruZ/kdmapper#70]
Hi, thanks for your work.

When I try to manual map my driver, I get BSOD and error code is "page fault in nonpaged area", any ideas?
 thank you very much

**Comment by TheCruZ** [comment]
If hello world driver loads fine there is a problem in your driver, make sure you are not using driver entry params, and you have set custom driver entry, page fault in non paged area just mean that an exception occurred in the memory area of your driver
