### ISSUE TITLE
The BaseOutputPath/OutputPath property is not set for project 'kdmapper.vcxproj'

### ISSUE THREAD

**Issue by DrkTheDon** [TheCruZ/kdmapper#71]
The BaseOutputPath/OutputPath property is not set for project 'kdmapper.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	kdmapper	E:\VSCODE2022\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	824

**Comment by TheCruZ** [comment]
Make sure your Visual Studio is working properly, and you download the entire source correctly
