### ISSUE TITLE
 Windows 11 22H2 not working

### ISSUE THREAD

**Issue by rootaydn** [TheCruZ/kdmapper#75]
It doesn't work in this version. Is there another alternative method that I can do?

**Comment by AhmedZero** [comment]
it worked for me.

**Comment by TheCruZ** [comment]
Please specify which issue you have

**Comment by czp541308303** [comment]
win11 build 22621  , status : STATUS_IMAGE_CERT_REVOKED

**Comment by xo1337** [comment]
Windows 11 Build 22621 Has revoked the certificate on the Intel Driver. You have to replace the vuln driver.

**Comment by AhmedZero** [comment]
my build is 22621 and it worked for me. but I disable two things.

**Comment by xo1337** [comment]
> my build is 22621 and it worked for me. but I disable two things.

What did you disable?

**Comment by Chener-03** [comment]
@AhmedZero How to do ,please

**Comment by AhmedZero** [comment]
1.
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Config\VulnerableDriverBlocklistEnable`
2.
Core Isolation 
https://support.content.office.net/en-us/media/c6329cf1-09c5-4e16-25a3-625d79ac70b8.png

**Comment by AhmedZero** [comment]
> @AhmedZero How to do ,please

Is it worked for you or you don't test yet?

**Comment by Chener-03** [comment]
> > @AhmedZero How to do ,please
> 
> Is it worked for you or you don't test yet?

not tested yet

**Comment by Chener-03** [comment]
> Is it worked? Because it worked for me 😄. I feel my PC is special case 😁.

It can be used

**Comment by FrazL123** [comment]
> > Is it worked? Because it worked for me 😄. I feel my PC is special case 😁.
> 
> It can be used

can someone confirm this

**Comment by FrazL123** [comment]
ok tested, kdmapper can work on windows 11 through turning off vulnerable drivers blocklist. HOWEVER, doing this stops any good games from loader, so a pointless fix

**Comment by unknownentity1337** [comment]
> Is it worked? Because it worked for me 😄. I feel my PC is special case 😁.

its worked for me , thanks bro  , my build : 22621.2134
