### ISSUE TITLE
STATUS_OBJECT_PATH_SYNTAX_BAD

### ISSUE THREAD

**Issue by zulqarnain1337** [TheCruZ/kdmapper#76]
I am using IoCreateDevice to create a device, but it returns the error

NTSTATUS DriverEntry(IN PDRIVER_OBJECT pDriverObject, IN PUNICODE_STRING pRegistryPath)
{
    UNREFERENCED_PARAMETER(pDriverObject);
    UNREFERENCED_PARAMETER(pRegistryPath);
    UNICODE_STRING drv_name;
    RtlInitUnicodeString(&drv_name, L"MyDriver1");
    return IoCreateDriver(&drv_name, &DriverInitializate);
}

NTSTATUS DriverInitializate(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath) {

    //Real Entry

    NTSTATUS status = STATUS_SUCCESS;
    PDEVICE_OBJECT deviceObject = NULL;
    UNICODE_STRING deviceName;
    UNICODE_STRING deviceLink;

    UNREFERENCED_PARAMETER(DriverObject);
    UNREFERENCED_PARAMETER(RegistryPath);

    //UNICODE_STRING symbolName;

    RtlInitUnicodeString(&deviceName, L"\\Device\\MyDriver1");
    RtlInitUnicodeString(&deviceLink, L"\\DosDevices\\MyDriver1");

    NTSTATUS ntStatus = IoCreateDevice(DriverObject, 0, &deviceName, FILE_DEVICE_UNKNOWN, FILE_DEVICE_SECURE_OPEN, FALSE, &deviceObject);

 if (!NT_SUCCESS(ntStatus))
    {
        DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, "IoCreateDevice failed %lx\n", ntStatus);
        return ntStatus;
    }
}

**Comment by TheCruZ** [comment]
I'm not sure since I don't do this, but probably windows have a check to detect someone doing this from allocated pool, try to do it from a valid memory, anyway the issue isn't 100% related to kdmapper
