### ISSUE TITLE
Check if driver is loaded and not loading twice

### ISSUE THREAD

**Issue by on51n** [TheCruZ/kdmapper#79]
How do i check if my Driver is already loaded so it can't be loaded twice

**Comment by saperex** [comment]
for example, use the CreateFile function, with the driver name, if it ends with INVALID_HANDLE_VALUE, then the driver is not loaded, and if it ends with a handle, then the driver is loaded.

**Comment by TheCruZ** [comment]
If you mean your mapped driver you must make your own method to know if it's loaded since kdmapper idea is hide completely that this driver is loaded
