### ISSUE TITLE
Hangs in calling intel_driver::CallKernelFunction

### ISSUE THREAD

**Issue by danyhm** [TheCruZ/kdmapper#84]
Hello,
my driver doesn't even gets to entry point and kdmapper hangs in resolving imports 
https://github.com/TheCruZ/kdmapper/blob/3a21e3a5a8955633d6b8fb159ae605420e44802e/kdmapper/kdmapper.cpp#L119

any ideas?

**Comment by TheCruZ** [comment]
Hi did you packed your driver in some way? If so you can try without pack it or try to debug where is the wrong reading and send a pull request to include into the source

**Comment by danyhm** [comment]
the driver is compiled with /GS option. your mapper works with /GS- option . does this mean I have to disable /GS ?

**Comment by TheCruZ** [comment]
Original driver entry params are not supported, this is not a real driver loading just calling driver entry on kernel this for example is an insta bsod:
https://github.com/wbenny/hvpp/blob/84b3f3c241e1eec3ab42f75cad9deef3ad67e6ab/src/hvppdrv_c/main.c#L36

**Comment by danyhm** [comment]
so many drivers rely on the input parameters. what is the correct way to handle this situation? can you point me to the right direction?

**Comment by danyhm** [comment]
The only idea i have is to use kdmapper to disable DSE temporarily anf then load my driver normaly and enable DSE again. This way patchguard won't trigger if the whole operation is done quickly
