### ISSUE TITLE
Error: 0xc0000409 Load driver cause bsod

### ISSUE THREAD

**Issue by BaiWin** [TheCruZ/kdmapper#89]
I tried to load different drivers in host machine or target machine but they all cause bsod.I tried to search online.But didnt find any solutions.Any advice will be appreciated.

[New Text Document.txt](https://github.com/TheCruZ/kdmapper/files/10303131/New.Text.Document.txt)

**Comment by TheCruZ** [comment]
It just bsod in your code, debug it and find your issue, try with the hello world driver just to verify that don't crash

**Comment by BaiWin** [comment]
Thx for replying! I'm new to driver coding.I did use hello world driver which follow the tutorial in msdn(https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver).I think the txt file I show is the dump file generated when loading the hello world driver with kdmapper.
