### ISSUE TITLE
How to set a custom driver entry?

### ISSUE THREAD

**Issue by BaiWin** [TheCruZ/kdmapper#91]
Hi, I have a question about how do you set the custom entry point. In your HelloWorld project, the driver entry point is "CustomDriverEntry". If I just modify it from Properties-link-advance-entry point, I'll get error " LINK2001 unresolved external symbol CustomEntry "when building the solution. I do this for modifying the entry point and loading my driver without bsod. Any advice would be appreciated.

**Comment by TheCruZ** [comment]
Create a function with the specifications of msdn for the driver entry and set on the project configuration with the same name of your function
