### ISSUE TITLE
Critical structure bsod

### ISSUE THREAD

**Issue by Sgamzat05** [TheCruZ/kdmapper#94]
After 10-20 minutes of running the driver, I get a bsod
[010823-9218-01.zip](https://github.com/TheCruZ/kdmapper/files/10367555/010823-9218-01.zip)

**Comment by TheCruZ** [comment]
As I can see in the BSOD your system detect a modification in the NtAddAtom function (function which get modified temporarily by kdmapper for the driver loading)

if this happens after 10-20 mins, and you didn't run kdmapper any more times and your driver don't keep kdmapper running then maybe Microsoft implemented checking of this kernel area in patch guard

**Comment by Sgamzat05** [comment]
it keep it running bcs i have while loop for readin in driver

**Comment by Sgamzat05** [comment]
That is, the bsod is obtained because of the keep running kdapper?

**Comment by TheCruZ** [comment]
Probably, kdmapper is designed in the way that you return from driver entry fast as you can, while your code get called in other way or use some kind of thread or execution context

**Comment by Sgamzat05** [comment]
> 

So I have to read the memory and close the driver? And then run it again for reading?
Or is it possible to somehow make the driver stay in the system and kdmapper shut down?

**Comment by TheCruZ** [comment]
If you check the requirements in the readme it says create a thread and return from your driver fastest as possible, you have to map your driver and create a thread to your code, when you return kdmapper will close and your code will run in your new thread

**Comment by Sgamzat05** [comment]
Thank you very much!
Is there an example of a driver creating a new thread?
