### ISSUE TITLE
BSOD with another thread

### ISSUE THREAD

**Issue by Sgamzat05** [TheCruZ/kdmapper#96]
Previously there was a problem that kdapper remained running and the bsod crashed after 10-20 minutes
I did the creation of a new thread, and now kdapper closes, but the bsod appears after 30 minutes or an hour
1 bsod dump from my pc, and second from friend's pc
![image](https://user-images.githubusercontent.com/46753195/212073216-e72467f5-151e-4720-b559-eef79cb45a80.png)
kdmapper is definitely closed, but the bsod remains
[011223-6484-01.zip](https://github.com/TheCruZ/kdmapper/files/10401701/011223-6484-01.zip)

[011223-6937-02.zip](https://github.com/TheCruZ/kdmapper/files/10401759/011223-6937-02.zip)

**Comment by TheCruZ** [comment]
18  : Kernel notification callout modification

BAD_STACK_0x109

dump shows 2 inconclusive errors and them seem related to you are doing
something wrong

**Comment by Sgamzat05** [comment]
I have loop that reads memory, if it works fine for 29 minutes, then what can happen at 30 minutes?

**Comment by Sgamzat05** [comment]
I have read file and read memory in loop

**Comment by Sgamzat05** [comment]
I think problem in PsSetLoadImageNotifyRoutine
Im using it in thread
What if i will use it in driverentry, then remove, and then create thread without it?

**Comment by TheCruZ** [comment]
PsSetLoadImageNotifyRoutine requires a callback and you callback will be in a pool unless you move your memory or callback and this will cause patch guard bsod
also, read memory is so extense you can get bsod by a lot of reasons

i will close this ticket since isn't related to kdmapper

**Comment by Sgamzat05** [comment]
Is there a way to avoid bsod when using a callback? I only need to use it once
